name: Generate QR Code

on:
  push:
    branches:
      - main
    paths:
      - "data/qrcode.py"
      - "data/data.csv" # 添加对data.csv的监控
  workflow_dispatch:

jobs:
  generate_qrcode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 确保获取完整的仓库历史

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install segno

      - name: Debug directory structure
        run: ls -R

      - name: Run QR code script
        run: python data/qrcode.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/img/
          git commit -m "Update QR codes" || exit 0
          git push
