name: Generate QR Code

on:
  push:
    paths:
      - "data/qrcode.py"
      - "data/data.csv"
  workflow_dispatch:

jobs:
  generate_qrcode:
    runs-on: ubuntu-latest
    # 关键点：授予写入权限
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # 关键点：使用 GITHUB_TOKEN 认证 checkout
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install segno

      - name: Run QR code script
        run: cd data && python qrcode.py && node convert.js

      - name: Commit and push changes
        env:
          # 关键点：使用内置的 GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated QR code generation"
          # 简化推送命令，利用已配置的 token
          git push origin HEAD:main
